import Tile from "./Tile";

const Game = ({ word, letters, currentRow, wordSplit, savedLetters, won }) => {
  return (
    <div className="Game">
      <div className="board-container">
        <div className="board">
          <div className="row">
            <Tile
              won={won}
              word={word}
              letters={letters}
              savedLetters={savedLetters}
              currentRow={currentRow}
              wordSplit={wordSplit}
              row={0}
              tileNum={0}
            />
            <Tile
              won={won}
              word={word}
              letters={letters}
              savedLetters={savedLetters}
              currentRow={currentRow}
              wordSplit={wordSplit}
              row={0}
              tileNum={1}
            />
            <Tile
              won={won}
              word={word}
              letters={letters}
              savedLetters={savedLetters}
              currentRow={currentRow}
              wordSplit={wordSplit}
              row={0}
              tileNum={2}
            />
            <Tile
              won={won}
              word={word}
              letters={letters}
              savedLetters={savedLetters}
              currentRow={currentRow}
              wordSplit={wordSplit}
              row={0}
              tileNum={3}
            />
            <Tile
              won={won}
              word={word}
              letters={letters}
              savedLetters={savedLetters}
              currentRow={currentRow}
              wordSplit={wordSplit}
              row={0}
              tileNum={4}
            />
          </div>
          <div className="row">
            <Tile
              won={won}
              word={word}
              letters={letters}
              savedLetters={savedLetters}
              currentRow={currentRow}
              wordSplit={wordSplit}
              row={1}
              tileNum={0}
            />
            <Tile
              won={won}
              word={word}
              letters={letters}
              savedLetters={savedLetters}
              currentRow={currentRow}
              wordSplit={wordSplit}
              row={1}
              tileNum={1}
            />
            <Tile
              won={won}
              word={word}
              letters={letters}
              savedLetters={savedLetters}
              currentRow={currentRow}
              wordSplit={wordSplit}
              row={1}
              tileNum={2}
            />
            <Tile
              won={won}
              word={word}
              letters={letters}
              savedLetters={savedLetters}
              currentRow={currentRow}
              wordSplit={wordSplit}
              row={1}
              tileNum={3}
            />
            <Tile
              won={won}
              word={word}
              letters={letters}
              savedLetters={savedLetters}
              currentRow={currentRow}
              wordSplit={wordSplit}
              row={1}
              tileNum={4}
            />
          </div>
          <div className="row">
            <Tile
              won={won}
              word={word}
              letters={letters}
              savedLetters={savedLetters}
              currentRow={currentRow}
              wordSplit={wordSplit}
              row={2}
              tileNum={0}
            />
            <Tile
              won={won}
              word={word}
              letters={letters}
              savedLetters={savedLetters}
              currentRow={currentRow}
              wordSplit={wordSplit}
              row={2}
              tileNum={1}
            />
            <Tile
              won={won}
              word={word}
              letters={letters}
              savedLetters={savedLetters}
              currentRow={currentRow}
              wordSplit={wordSplit}
              row={2}
              tileNum={2}
            />
            <Tile
              won={won}
              word={word}
              letters={letters}
              savedLetters={savedLetters}
              currentRow={currentRow}
              wordSplit={wordSplit}
              row={2}
              tileNum={3}
            />
            <Tile
              won={won}
              word={word}
              letters={letters}
              savedLetters={savedLetters}
              currentRow={currentRow}
              wordSplit={wordSplit}
              row={2}
              tileNum={4}
            />
          </div>
          <div className="row">
            <Tile
              won={won}
              word={word}
              letters={letters}
              savedLetters={savedLetters}
              currentRow={currentRow}
              wordSplit={wordSplit}
              row={3}
              tileNum={0}
            />
            <Tile
              won={won}
              word={word}
              letters={letters}
              savedLetters={savedLetters}
              currentRow={currentRow}
              wordSplit={wordSplit}
              row={3}
              tileNum={1}
            />
            <Tile
              won={won}
              word={word}
              letters={letters}
              savedLetters={savedLetters}
              currentRow={currentRow}
              wordSplit={wordSplit}
              row={3}
              tileNum={2}
            />
            <Tile
              won={won}
              word={word}
              letters={letters}
              savedLetters={savedLetters}
              currentRow={currentRow}
              wordSplit={wordSplit}
              row={3}
              tileNum={3}
            />
            <Tile
              won={won}
              word={word}
              letters={letters}
              savedLetters={savedLetters}
              currentRow={currentRow}
              wordSplit={wordSplit}
              row={3}
              tileNum={4}
            />
          </div>
          <div className="row">
            <Tile
              won={won}
              word={word}
              letters={letters}
              savedLetters={savedLetters}
              currentRow={currentRow}
              wordSplit={wordSplit}
              row={4}
              tileNum={0}
            />
            <Tile
              won={won}
              word={word}
              letters={letters}
              savedLetters={savedLetters}
              currentRow={currentRow}
              wordSplit={wordSplit}
              row={4}
              tileNum={1}
            />
            <Tile
              won={won}
              word={word}
              letters={letters}
              savedLetters={savedLetters}
              currentRow={currentRow}
              wordSplit={wordSplit}
              row={4}
              tileNum={2}
            />
            <Tile
              won={won}
              word={word}
              letters={letters}
              savedLetters={savedLetters}
              currentRow={currentRow}
              wordSplit={wordSplit}
              row={4}
              tileNum={3}
            />
            <Tile
              won={won}
              word={word}
              letters={letters}
              savedLetters={savedLetters}
              currentRow={currentRow}
              wordSplit={wordSplit}
              row={4}
              tileNum={4}
            />
          </div>
          <div className="row">
            <Tile
              won={won}
              word={word}
              letters={letters}
              savedLetters={savedLetters}
              currentRow={currentRow}
              wordSplit={wordSplit}
              row={5}
              tileNum={0}
            />
            <Tile
              won={won}
              word={word}
              letters={letters}
              savedLetters={savedLetters}
              currentRow={currentRow}
              wordSplit={wordSplit}
              row={5}
              tileNum={1}
            />
            <Tile
              won={won}
              word={word}
              letters={letters}
              savedLetters={savedLetters}
              currentRow={currentRow}
              wordSplit={wordSplit}
              row={5}
              tileNum={2}
            />
            <Tile
              won={won}
              word={word}
              letters={letters}
              savedLetters={savedLetters}
              currentRow={currentRow}
              wordSplit={wordSplit}
              row={5}
              tileNum={3}
            />
            <Tile
              won={won}
              word={word}
              letters={letters}
              savedLetters={savedLetters}
              currentRow={currentRow}
              wordSplit={wordSplit}
              row={5}
              tileNum={4}
            />
          </div>
        </div>
      </div>
    </div>
  );
};

export default Game;
